ALTER TABLE livres
    ADD COLUMN IF NOT EXISTS bio_auteur TEXT DEFAULT NULL AFTER description,
    ADD COLUMN IF NOT EXISTS pages INT DEFAULT NULL AFTER bio_auteur,
    ADD COLUMN IF NOT EXISTS editeur VARCHAR(120) DEFAULT NULL AFTER pages,
    ADD COLUMN IF NOT EXISTS note DECIMAL(2, 1) DEFAULT NULL AFTER editeur;
