-- Ajout de livres disponibles, empruntes et reserves (ignore si deja presents)
INSERT IGNORE INTO livres (titre, auteur, isbn, categorie, annee, statut, prix, description, bio_auteur, pages, editeur, note) VALUES
('Le Seigneur des Anneaux', 'J.R.R. Tolkien', '978-2267020098', 'Fantasy', 1954, 'disponible', 24.90,
 'Frodon entreprend un voyage epique pour detruire un anneau maléfique et sauver la Terre du Milieu.',
 'J.R.R. Tolkien, philologue et romancier britannique, a cree un univers fantasy de reference.',
 1216, 'Christian Bourgois', 4.9),
('Dune', 'Frank Herbert', '978-2266326047', 'Science-Fiction', 1965, 'disponible', 21.50,
 'Sur la planete desertique Arrakis, plusieurs factions s affrontent pour le controle de l epice.',
 'Frank Herbert est considere comme l un des maitres de la science-fiction moderne.',
 688, 'Pocket', 4.6),
('La Peste', 'Albert Camus', '978-2070360100', 'Philosophie', 1947, 'emprunte', 13.20,
 'A Oran, une epidemie de peste confine la ville et oblige chacun a affronter l absurdite et la solidarite.',
 'Albert Camus developpe ici sa reflexion sur la condition humaine face au malheur collectif.',
 320, 'Gallimard', 4.4),
('Le Rouge et le Noir', 'Stendhal', '978-2253003159', 'Classique', 1830, 'emprunte', 15.80,
 'Julien Sorel, ambitieux et passionne, gravit les echelons de la societe sous la Restauration.',
 'Stendhal, pionnier du roman realiste, decrit avec finesse les passions et les hypocrisies sociales.',
 576, 'Livre de Poche', 4.3),
('Germinal', 'Emile Zola', '978-2253003937', 'Classique', 1885, 'emprunte', 17.40,
 'Dans le nord minier, Etienne Lantier decouvre la misere ouvriere et la force des luttes sociales.',
 'Emile Zola, chef de file du naturalisme, peint avec force la vie des travailleurs du XIXe siecle.',
 592, 'Livre de Poche', 4.5),
('La Nausee', 'Jean-Paul Sartre', '978-2070360027', 'Philosophie', 1938, 'reserve', 12.90,
 'Antoine Roquentin, a Bouville, est traverse par une crise existentielle qui remet en question le reel.',
 'Jean-Paul Sartre, philosophe et ecrivain, est une figure centrale de l existentialisme.',
 256, 'Gallimard', 4.2),
('Le Parfum', 'Patrick Suskind', '978-2253014278', 'Fiction', 1985, 'reserve', 14.60,
 'Jean-Baptiste Grenouille, ne sans odeur, devient un genie olfactif obsede par la creation du parfum parfait.',
 'Patrick Suskind a connu un succes mondial avec ce roman singulier et hypnotique.',
 336, 'Livre de Poche', 4.5),
('Bel-Ami', 'Guy de Maupassant', '978-2253003287', 'Classique', 1885, 'reserve', 11.90,
 'Georges Duroy, journaliste sans scrupules, utilise charme et manipulation pour gravir les echelons parisiennes.',
 'Guy de Maupassant, maitre de la nouvelle, decrit ici la societe parisienne avec mordant.',
 416, 'Livre de Poche', 4.1);
